/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MultiplasTelas;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaRelatorio extends javax.swing.JFrame {
    LinkedList<Pessoa> listaPessoas;
    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio(LinkedList<Pessoa> listaPessoas) {
        initComponents();
        this.listaPessoas = listaPessoas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jBVerificar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jCBTamanho = new javax.swing.JCheckBox();
        jCBMediaIdades = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Oi! Sou a tela de relatório.");

        jBVerificar.setText("Verificar");
        jBVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jCBTamanho.setText(" Tamanho da lista");

        jCBMediaIdades.setText("Media das idades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBTamanho)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBVerificar)
                                .addGap(52, 52, 52)
                                .addComponent(jBCancelar))
                            .addComponent(jCBMediaIdades))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jCBTamanho)
                .addGap(13, 13, 13)
                .addComponent(jCBMediaIdades)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVerificar)
                    .addComponent(jBCancelar))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarActionPerformed
        // TODO add your handling code here:
        if(jCBTamanho.isSelected()){
           JOptionPane.showMessageDialog(rootPane, "Tamanho " + this.listaPessoas.size());

        }
        if (jCBMediaIdades.isSelected()){
            int somaIdade = 0;
            for (int x =0; x < listaPessoas.size(); x++){
                Pessoa minhaPessoa = listaPessoas.get(x);
                somaIdade = minhaPessoa.getIdade() + somaIdade;
            }
            float mediaIdade = somaIdade/listaPessoas.size();
            JOptionPane.showMessageDialog(rootPane, "Média das idades é " + mediaIdade);
        }
    }//GEN-LAST:event_jBVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBVerificar;
    private javax.swing.JCheckBox jCBMediaIdades;
    private javax.swing.JCheckBox jCBTamanho;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
