/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class ExemploCheckRadio extends javax.swing.JFrame {

    /**
     * Creates new form ExemploCheckRadio
     */
    public ExemploCheckRadio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGOpcoes = new javax.swing.ButtonGroup();
        jLTituloTeste = new javax.swing.JLabel();
        jCBCheckOpcao2 = new javax.swing.JCheckBox();
        jCBCheckOpcao3 = new javax.swing.JCheckBox();
        jCBCheckOpcao1 = new javax.swing.JCheckBox();
        jBVerificarCheck = new javax.swing.JButton();
        jBReiniciarCheck = new javax.swing.JButton();
        jLTituloRadio = new javax.swing.JLabel();
        jRBRadioOpcao1 = new javax.swing.JRadioButton();
        jRBRadioOpcao2 = new javax.swing.JRadioButton();
        jRBRadioOpcao3 = new javax.swing.JRadioButton();
        jBVerificarRadio = new javax.swing.JButton();
        jBReiniciarRadio = new javax.swing.JButton();
        jLSenha = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jBVerificarSenha = new javax.swing.JButton();
        jLUsuario = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTituloTeste.setText("Deseja:");

        jCBCheckOpcao2.setText("Opção 2");

        jCBCheckOpcao3.setText("Opção 3");

        jCBCheckOpcao1.setText("Opção 1");

        jBVerificarCheck.setText("Verificar Check");
        jBVerificarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarCheckActionPerformed(evt);
            }
        });

        jBReiniciarCheck.setText("Reiniciar Check");
        jBReiniciarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReiniciarCheckActionPerformed(evt);
            }
        });

        jLTituloRadio.setText("Escolhe qual opção:");

        bGOpcoes.add(jRBRadioOpcao1);
        jRBRadioOpcao1.setText("Opção 1");

        bGOpcoes.add(jRBRadioOpcao2);
        jRBRadioOpcao2.setText("Opção 2");

        bGOpcoes.add(jRBRadioOpcao3);
        jRBRadioOpcao3.setText("Opção 3");

        jBVerificarRadio.setText("Verificar Radio");
        jBVerificarRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarRadioActionPerformed(evt);
            }
        });

        jBReiniciarRadio.setText("Reiniciar Radio");
        jBReiniciarRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReiniciarRadioActionPerformed(evt);
            }
        });

        jLSenha.setText("Senha");

        jBVerificarSenha.setText("Verificar Senha");
        jBVerificarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarSenhaActionPerformed(evt);
            }
        });

        jLUsuario.setText("Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCBCheckOpcao1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBCheckOpcao2)
                                .addComponent(jCBCheckOpcao3))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBVerificarCheck)
                                .addComponent(jBReiniciarCheck)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jLTituloTeste))
                        .addComponent(jLSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRBRadioOpcao1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jLTituloRadio)))
                            .addGap(130, 130, 130))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRBRadioOpcao2)
                                .addComponent(jRBRadioOpcao3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBReiniciarRadio)
                                .addComponent(jBVerificarRadio))
                            .addGap(64, 64, 64)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(204, 204, 204))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBVerificarSenha)
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTituloTeste)
                        .addGap(18, 18, 18)
                        .addComponent(jCBCheckOpcao1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTituloRadio)
                        .addGap(18, 18, 18)
                        .addComponent(jRBRadioOpcao1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCheckOpcao2)
                    .addComponent(jBVerificarCheck)
                    .addComponent(jRBRadioOpcao2)
                    .addComponent(jBVerificarRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCheckOpcao3)
                    .addComponent(jBReiniciarCheck)
                    .addComponent(jRBRadioOpcao3)
                    .addComponent(jBReiniciarRadio))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSenha)
                    .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBVerificarSenha)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVerificarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarCheckActionPerformed
        // TODO add your handling code here:
        if(jCBCheckOpcao1.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Check opção 1 selecionado");
        }
        if(jCBCheckOpcao2.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Check opção 2 selecionado");
        }
        if(jCBCheckOpcao3.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Check opção 3 selecionado");
        }
    }//GEN-LAST:event_jBVerificarCheckActionPerformed

    private void jBReiniciarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReiniciarCheckActionPerformed
        // TODO add your handling code here:
        jCBCheckOpcao1.setSelected(false);
        jCBCheckOpcao2.setSelected(false);
        jCBCheckOpcao3.setSelected(false);
    }//GEN-LAST:event_jBReiniciarCheckActionPerformed

    private void jBVerificarRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarRadioActionPerformed
        // TODO add your handling code here:
        if(jRBRadioOpcao1.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Radio opção 1 selecionado");
        } else if(jRBRadioOpcao2.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Radio opção 2 selecionado");
        } else if(jRBRadioOpcao3.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Radio opção 3 selecionado");
        }
    }//GEN-LAST:event_jBVerificarRadioActionPerformed

    private void jBReiniciarRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReiniciarRadioActionPerformed
        // TODO add your handling code here:
        jRBRadioOpcao1.setSelected(true);
    }//GEN-LAST:event_jBReiniciarRadioActionPerformed

    private void jBVerificarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarSenhaActionPerformed
        // TODO add your handling code here:
        String usuario = jTFUsuario.getText();
        String senha = new String(jPFSenha.getPassword());
        if(usuario.equals("Robson") && senha.equals("admin")){
            JOptionPane.showMessageDialog(rootPane, "Beleza!!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Você não é o Robson!");
        }
    }//GEN-LAST:event_jBVerificarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExemploCheckRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExemploCheckRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExemploCheckRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExemploCheckRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExemploCheckRadio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGOpcoes;
    private javax.swing.JButton jBReiniciarCheck;
    private javax.swing.JButton jBReiniciarRadio;
    private javax.swing.JButton jBVerificarCheck;
    private javax.swing.JButton jBVerificarRadio;
    private javax.swing.JButton jBVerificarSenha;
    private javax.swing.JCheckBox jCBCheckOpcao1;
    private javax.swing.JCheckBox jCBCheckOpcao2;
    private javax.swing.JCheckBox jCBCheckOpcao3;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLTituloRadio;
    private javax.swing.JLabel jLTituloTeste;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JRadioButton jRBRadioOpcao1;
    private javax.swing.JRadioButton jRBRadioOpcao2;
    private javax.swing.JRadioButton jRBRadioOpcao3;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
